# Generated by Django 3.2.4 on 2021-10-01 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('HR', 'HR'), ('Trainee', 'Trainee'), ('IDK', 'IDK')], default='HR', max_length=250)),
                ('role', models.CharField(choices=[('role1', 'role1'), ('role2', 'role2'), ('role3', 'role3')], default='role1', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
