# Generated by Django 3.2.4 on 2021-10-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
    ]
