# Generated by Django 3.2.8 on 2021-11-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
