# Generated by Django 3.2.8 on 2021-11-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hangman_word', models.CharField(max_length=250)),
                ('question', models.CharField(max_length=2000)),
                ('right_option', models.CharField(max_length=1000)),
                ('first_wrong_option', models.CharField(max_length=1000)),
                ('second_wrong_option', models.CharField(max_length=1000)),
                ('third_wrong_option', models.CharField(max_length=1000)),
                ('explanation', models.CharField(max_length=1000)),
            ],
        ),
    ]
