# Generated by Django 3.2.5 on 2021-10-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0002_auto_20211008_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='department',
            field=models.CharField(choices=[('HR', 'HR'), ('HOD', 'HOD'), ('Trainer', 'Trainer')], default=0, max_length=250),
            preserve_default=False,
        ),
    ]
