# Generated by Django 3.2.8 on 2021-11-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0002_module5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module1',
            name='word1',
        ),
        migrations.RemoveField(
            model_name='module1',
            name='word2',
        ),
        migrations.RemoveField(
            model_name='module2',
            name='word1',
        ),
        migrations.RemoveField(
            model_name='module2',
            name='word2',
        ),
        migrations.AddField(
            model_name='module1',
            name='explanation',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module2',
            name='explanation',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module3',
            name='explanation',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
