# Generated by Django 3.2.8 on 2021-10-23 04:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0003_customer_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='department',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('HR', 'HR'), ('HOD', 'HOD'), ('Trainer', 'Trainer')], max_length=14),
        ),
    ]
