# Generated by Django 3.2.8 on 2021-10-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0005_alter_customer_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
