# Generated by Django 3.2.8 on 2021-10-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0006_model1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model1',
            new_name='Module1',
        ),
    ]
