# Generated by Django 3.2.8 on 2021-10-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0007_rename_model1_module1'),
    ]

    operations = [
        migrations.AddField(
            model_name='module1',
            name='first_wrong_option',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module1',
            name='question',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module1',
            name='right_option',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module1',
            name='second_wrong_option',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module1',
            name='third_wrong_option',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module1',
            name='word1',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module1',
            name='word2',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
