# Generated by Django 3.2.8 on 2021-10-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0008_auto_20211027_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=250)),
                ('word2', models.CharField(max_length=250)),
                ('question', models.CharField(max_length=2000)),
                ('right_option', models.CharField(max_length=1000)),
                ('first_wrong_option', models.CharField(max_length=1000)),
                ('second_wrong_option', models.CharField(max_length=1000)),
                ('third_wrong_option', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Module3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=250)),
                ('word2', models.CharField(max_length=250)),
                ('question', models.CharField(max_length=2000)),
                ('right_option', models.CharField(max_length=1000)),
                ('first_wrong_option', models.CharField(max_length=1000)),
                ('second_wrong_option', models.CharField(max_length=1000)),
                ('third_wrong_option', models.CharField(max_length=1000)),
            ],
        ),
    ]
