# Generated by Django 3.2.8 on 2021-10-27 08:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0009_module2_module3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='department',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('HR', 'HR'), ('Trainer', 'Trainer'), ('Trainee', 'Trainee')], max_length=18),
        ),
    ]
