# Generated by Django 3.2.8 on 2021-10-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0010_alter_customer_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='department',
        ),
        migrations.AddField(
            model_name='customer',
            name='hr',
            field=models.BooleanField(default=False, verbose_name='HR'),
        ),
        migrations.AddField(
            model_name='customer',
            name='trainee',
            field=models.BooleanField(default=False, verbose_name='Trainee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='trainer',
            field=models.BooleanField(default=False, verbose_name='Trainer'),
        ),
    ]
