# Generated by Django 3.2.8 on 2021-10-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0011_auto_20211028_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
