# Generated by Django 3.2.8 on 2021-10-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0012_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
