# Generated by Django 3.2.8 on 2021-11-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0014_remove_customer_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hangman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
