# Generated by Django 3.2.8 on 2021-11-01 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0015_hangman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hangman',
            options={'ordering': ['word']},
        ),
        migrations.RenameField(
            model_name='hangman',
            old_name='Word',
            new_name='word',
        ),
        migrations.RemoveField(
            model_name='hangman',
            name='slug',
        ),
        migrations.AddField(
            model_name='hangman',
            name='word_hint',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, unique=True)),
                ('question_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marineapp.hangman')),
            ],
        ),
    ]
